var child = [
  { 'dupe': false, 'type': 4, 'name': '_me_lab7', 'dir': 'c0', 'linked': 5, 'url': 'http://kacperzielinski.pl/_me_lab7/', 'fetched': true, 'code': 200, 'len': 1011, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 41, 'issue_cnt': [ 30, 2, 7, 21, 0 ], 'sig': 0x4e246a26 },
  { 'dupe': false, 'type': 4, 'name': '_me_lab7', 'dir': 'c1', 'linked': 2, 'url': 'http://kacperzielinski.pl/_me_lab7/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 4, 0, 0, 0, 0 ], 'sig': 0x7d5975a1 },
  { 'dupe': false, 'type': 4, 'name': '_me_lab7', 'dir': 'c2', 'linked': 2, 'url': 'http://kacperzielinski.pl/_me_lab7/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 0, 'issue_cnt': [ 3, 1, 2, 0, 0 ], 'sig': 0xa1acb5a1 },
  { 'dupe': true, 'type': 4, 'name': '_me_lab7', 'dir': 'c3', 'linked': 2, 'url': 'http://kacperzielinski.pl/_me_lab7/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x7d5975a1 },
  { 'dupe': false, 'type': 4, 'name': 'home', 'dir': 'c4', 'linked': 1, 'url': 'http://kacperzielinski.pl/home/', 'fetched': true, 'code': 404, 'len': 1203, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x294f5293 },
  { 'dupe': false, 'type': 4, 'name': 'icons', 'dir': 'c5', 'linked': 2, 'url': 'http://kacperzielinski.pl/icons/', 'fetched': true, 'code': 200, 'len': 74798, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 46, 'issue_cnt': [ 7, 0, 0, 0, 0 ], 'sig': 0xf32f6aeb },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c6', 'linked': 2, 'url': 'http://kacperzielinski.pl/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 797, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c7', 'linked': 2, 'url': 'http://kacperzielinski.pl/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 797, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
