var child = [
  { 'dupe': false, 'type': 128, 'name': '100', 'dir': 'c0', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=100&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '101', 'dir': 'c1', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=101&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '123412341234567856785678', 'dir': 'c2', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=123412341234567856785678&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '123456789012345678', 'dir': 'c3', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=123456789012345678&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '89', 'dir': 'c4', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=89&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '90', 'dir': 'c5', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=90&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '91', 'dir': 'c6', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=91&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '92', 'dir': 'c7', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=92&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '93', 'dir': 'c8', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=93&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '94', 'dir': 'c9', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=94&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '95', 'dir': 'c10', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=95&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '96', 'dir': 'c11', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=96&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '97', 'dir': 'c12', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=97&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '98', 'dir': 'c13', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=98&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff },
  { 'dupe': true, 'type': 128, 'name': '99', 'dir': 'c14', 'linked': 0, 'url': 'http://kacperzielinski.pl/_me_lab7/web/transferForm.php DATA:name=Smith&account=99&zl=1&gr=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7fffff }
];
